name: Common pre-commit checks

on:
  workflow_call:
    secrets:
      GHA_TOKEN:
        required: true
    inputs:
      INSTALL_ARGS:
        required: false
        type: string

jobs:
  check:
    runs-on:
      group: Default
      labels: self-hosted
    container: ghcr.io/oxionics/poetry:1.30-py3.10
    name: Common pre-commit checks
    steps:
      - uses: OxIonics/poetry-preamble@master
        with:
          INSTALL_ARGS: ${{ inputs.INSTALL_ARGS }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
        env:
          RUFF_OUTPUT_FORMAT: github
