name: Package

on:
  workflow_call:
    secrets:
      PYPI_SERVER:
        required: true
      PYPI_LOGIN:
        required: true
      PYPI_PASSWORD:
        required: true
    inputs:
      EXTRA_POETRY_INJECT_ARGS:
        required: false
        default: ""
        type: string
      CHECK_PACKAGE_VERSION:
        required: false
        default: true
        type: boolean
      RUST_TOOLCHAIN:
        required: false
        default: ""
        type: string
      RUST_COMPONENTS:
        required: false
        default: ""
        type: string
      UBUNTU_VERSION:
        required: false
        default: "20.04"
        type: string

jobs:
  build_windows_wheel:
    name: Build wheels for Python ${{ matrix.python }} on Windows
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install specific pip version
        run: python3 -m pip install --upgrade pip==21.3.1

      - name: Install Poetry, etc...
        run: |
          pip install pipx==1.1.0
          pipx install poetry==2.1.1
          pipx install poethepoet==0.33.1
          pipx inject poetry poetry-dynamic-versioning[plugin]==1.8.2

      - uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
        with:
          toolchain: ${{ inputs.RUST_TOOLCHAIN }}
          override: true
          components: ${{ inputs.RUST_COMPONENTS }}
          rustflags: ""

      - name: Check poetry lock file
        run: poetry check --lock

      - name: Check package versions
        uses: OxIonics/common-actions/check-poetry-version@jjc/check-poetry-version

      - name: Build wheel
        run: poetry build -f wheel

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-windows-py${{ matrix.python }}
          path: ./dist/*whl
          if-no-files-found: error
          retention-days: 1

  build_linux_wheel:
    name: Build wheels for Python ${{ matrix.python }} on Linux
    container:
      image: ghcr.io/oxionics/poetry:1.30-py${{ matrix.python }}
    runs-on:
      group: Default
      labels: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Poetry dynamic versioning
        run: pipx inject poetry poetry-dynamic-versioning[plugin]==1.8.2 ${{ inputs.EXTRA_POETRY_INJECT_ARGS }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
        with:
          toolchain: ${{ inputs.RUST_TOOLCHAIN }}
          override: true
          components: ${{ inputs.RUST_COMPONENTS }}
          rustflags: ""

      - name: Check poetry lock file
        run: poetry check --lock

      - name: Check package versions
        uses: OxIonics/common-actions/check-poetry-version@jjc/check-poetry-version

      - name: Build wheel
        run: poetry build -f wheel

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-linux-py${{ matrix.python }}
          path: ./dist/*whl
          if-no-files-found: error
          retention-days: 1

  upload_wheels:
    needs: [build_linux_wheel, build_windows_wheel]
    if: github.event_name == 'push'
    container: ghcr.io/oxionics/poetry:1.30-py3.10
    runs-on:
      group: Default
      labels: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if files other than poetry.lock have changed
        id: poetry-lock-changed
        uses: tj-actions/changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b
        with:
          files: poetry.lock

      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Extract wheels
        run: |
          mkdir -p dist
          mv artifacts/*/* dist

      - name: Install Poetry dynamic versioning
        run: pipx inject poetry poetry-dynamic-versioning[plugin]==1.8.2 ${{ inputs.EXTRA_POETRY_INJECT_ARGS }}

      - name: Configure poetry
        run: |
          poetry config repositories.oxionics ${{ secrets.PYPI_SERVER }}
          poetry config http-basic.oxionics \
            ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASSWORD }}

      - name: Upload wheel
        if: |
          steps.poetry-lock-changed.outcome == 'skipped' ||
          steps.poetry-lock-changed.outputs.only_modified == 'false'
        run: poetry publish -r oxionics
        env:
          PIP_REQUESTS_TIMEOUT: 300
          POETRY_REQUESTS_TIMEOUT: 300
