name: Package

on:
  workflow_call:
    secrets:
      PYPI_SERVER:
        required: true
      PYPI_LOGIN:
        required: true
      PYPI_PASSWORD:
        required: true
    inputs:
      EXTRA_POETRY_PIP_ARGS:
        required: false
        default: ""
        type: string

jobs:
  build_and_upload_wheel:
    name: Build and upload wheel
    container:
      image: ghcr.io/oxionics/poetry:1.11
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Poetry dynamic versioning
        run: pipx inject poetry poetry-dynamic-versioning==0.13.1 ${{ inputs.EXTRA_POETRY_PIP_ARGS }}

      - name: Build wheel
        run: poetry build -f wheel

      - name: Configure poetry
        if: github.event_name == 'push'
        run: |
          poetry config repositories.oxionics ${{ secrets.PYPI_SERVER }}
          poetry config http-basic.oxionics \
            ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASSWORD }}

      - name: Upload wheel
        if: github.event_name == 'push'
        run: poetry publish -r oxionics
