name: Package

on:
  workflow_call:
    secrets:
      PYPI_SERVER:
        required: true
      PYPI_LOGIN:
        required: true
      PYPI_PASSWORD:
        required: true
    inputs:
      EXTRA_POETRY_INJECT_ARGS:
        required: false
        default: ""
        type: string
      CHECK_PACKAGE_VERSION:
        required: false
        default: true
        type: boolean

jobs:
  build_and_upload_wheel:
    name: Build and upload wheel
    container:
      image: ghcr.io/oxionics/poetry:1.30-py3.10
    runs-on:
      group: Default
      labels: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Poetry dynamic versioning
        run: pipx inject poetry poetry-dynamic-versioning[plugin]==1.8.2 ${{ inputs.EXTRA_POETRY_INJECT_ARGS }}

      - name: Set default Rust toolchain
        run: rustup default stable

      - name: Check poetry lock file
        run: poetry check --lock

      - name: Check package versions
        uses: OxIonics/common-actions/check-poetry-version@jjc/check-poetry-version

      - name: Build wheel
        run: poetry build -f wheel

      - id: poetry-lock-exists
        if: github.event_name == 'push'
        uses: andstor/file-existence-action@v2
        with:
          files: poetry.lock
      - name: Check if files other than poetry.lock have changed
        if: |
          github.event_name == 'push' &&
          steps.poetry-lock-exists.outputs.file_exists == 'true'
        id: poetry-lock-changed
        uses: tj-actions/changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b
        with:
            files: poetry.lock
      - name: Configure poetry
        if: |
          github.event_name == 'push' && (
            steps.poetry-lock-changed.outcome == 'skipped' ||
            steps.poetry-lock-changed.outputs.only_modified == 'false'
          )
        run: |
          poetry config repositories.oxionics ${{ secrets.PYPI_SERVER }}
          poetry config http-basic.oxionics \
            ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASSWORD }}

      - name: Upload wheel
        if: |
          github.event_name == 'push' && (
              steps.poetry-lock-changed.outcome == 'skipped' ||
              steps.poetry-lock-changed.outputs.only_modified == 'false'
          )
        run: poetry publish -r oxionics
        env:
          PIP_REQUESTS_TIMEOUT: 300
          POETRY_REQUESTS_TIMEOUT: 300
