on:
  pull_request:
    types: [review_requested]
jobs:
  softies_review_requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.requested_team.name == 'softies'}}
    steps:
    - name: "Post a message in #softies-review-requests"
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SOFTIES_REVIEW_REQUEST_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          text: "<${{ github.event.pull_request.html_url }}|${{ github.event.repository.name }}#${{ github.event.pull_request.number }}> ${{ github.event.pull_request.title }}"
