on:
  workflow_call:
    secrets:
      GHA_TOKEN:
        required: true
    inputs:
      INSTALL_ARGS:
        required: false
        type: string
      RUN_TESTS:
        required: false
        default: true
        type: boolean

jobs:
  # we can't reuse the sibling test workflow here because we're limited to a
  # workflow depth of 2.
  test:
    if: ${{ inputs.RUN_TESTS }}
    strategy:
      matrix:
        python: ["3.10"]
    runs-on:
      group: Default
      labels: self-hosted
    container: ghcr.io/oxionics/poetry:1.23-py${{ matrix.python }}
    name: Unit Tests (Python ${{ matrix.python }})
    steps:
      - uses: OxIonics/poetry-preamble@master
        with:
          INSTALL_ARGS: ${{ inputs.INSTALL_ARGS }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          PYTHON_VERSION: ${{ matrix.python }}

      - name: Test
        run: poe test-py

  flake8:
    runs-on:
      group: Default
      labels: self-hosted
    container: ghcr.io/oxionics/poetry:1.23-py3.10
    name: Flake8
    steps:
      - uses: OxIonics/poetry-preamble@master
        with:
          INSTALL_ARGS: ${{ inputs.INSTALL_ARGS }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Flake8
        run: poe flake

  black:
    runs-on:
      group: Default
      labels: self-hosted
    container: ghcr.io/oxionics/poetry:1.23-py3.10
    name: Formatting check
    steps:
      - uses: OxIonics/poetry-preamble@master
        with:
          INSTALL_ARGS: ${{ inputs.INSTALL_ARGS }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Black check
        run: poe fmt-test-py
