name: Package

on:
  workflow_call:
    secrets:
      GHA_TOKEN:
        required: true
    inputs:
      INSTALL_ARGS:
        required: false
        type: string
      TEST_TASK:
        required: false
        type: string
        default: test



jobs:
  test:
    runs-on: self-hosted
    container: ghcr.io/oxionics/poetry:1.20
    name: Unit Tests
    steps:
      - uses: OxIonics/poetry-preamble@master
        with:
          INSTALL_ARGS: ${{ inputs.INSTALL_ARGS }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Test
        run: poe ${{ inputs.TEST_TASK }}
