name: Package

on:
  workflow_call:
    inputs:
      TEST_PATH:
        required: false
        default: .
        type: string
      INSTALL_ARGS:
        required: false
        type: string



jobs:
  test:
    runs-on: self-hosted
    container: ghcr.io/oxionics/poetry:1.5
    name: Unit Tests
    steps:
      - uses: OxIonics/poetry-preamble@master
        with:
          INSTALL_ARGS: ${{ inputs.INSTALL_ARGS }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Test
        run: $POETRY run pytest -v ${{ inputs.TEST_PATH }}
