name: Package

on:
  workflow_call:
    secrets:
      GHA_TOKEN:
        required: true
    inputs:
      INSTALL_ARGS:
        required: false
        type: string
      TEST_TASK:
        required: false
        type: string
        default: test
      CACHE_VIRTUAL_ENV:
        description: Cache the python virtual env
        required: false
        # Ideally this would be a boolean but you can't have non-string defaults
        # in actions
        type: string
        default: "true"



jobs:
  test:
    strategy:
      matrix:
        python: ["3.10", "3.12"]
    runs-on:
      group: Default
      labels: self-hosted
    container: ghcr.io/oxionics/poetry:1.31-py${{ matrix.python }}
    name: Unit Tests (Python ${{ matrix.python }})
    steps:
      - uses: OxIonics/poetry-preamble@master
        with:
          INSTALL_ARGS: ${{ inputs.INSTALL_ARGS }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          PYTHON_VERSION: ${{ matrix.python }}
          CACHE_VIRTUAL_ENV: ${{ inputs.CACHE_VIRTUAL_ENV }}

      - name: Test
        run: poe ${{ inputs.TEST_TASK }}
