name: Package

on:
  workflow_call:
    secrets:
      GHA_TOKEN:
        required: true
    inputs:
      INSTALL_ARGS:
        required: false
        type: string
      TEST_TASK:
        required: false
        type: string
        default: test



jobs:
  test:
    strategy:
      matrix:
        python: ["3.10"]
    runs-on:
      group: Default
      labels: self-hosted
    container: ghcr.io/oxionics/poetry:1.23-py${{ matrix.python }}
    name: Unit Tests (Python ${{ matrix.python }})
    steps:
      - uses: OxIonics/poetry-preamble@master
        with:
          INSTALL_ARGS: ${{ inputs.INSTALL_ARGS }}
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
          PYTHON_VERSION: ${{ matrix.python }}

      - name: Test
        run: poe ${{ inputs.TEST_TASK }}
